//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrServer.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class charsoog_BrDBEntities : DbContext
    {
        public charsoog_BrDBEntities()
            : base("name=charsoog_BrDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Character> Characters { get; set; }
        public virtual DbSet<Emote> Emotes { get; set; }
        public virtual DbSet<Flag> Flags { get; set; }
        public virtual DbSet<Parachute> Parachutes { get; set; }
        public virtual DbSet<Player> Players { get; set; }
    }
}
