//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrServer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Player()
        {
            this.Characters = new HashSet<Character>();
            this.Emotes = new HashSet<Emote>();
            this.Flags = new HashSet<Flag>();
            this.Parachutes = new HashSet<Parachute>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int CurrentCharacter { get; set; }
        public int CurrentFlag { get; set; }
        public int CurrentPara { get; set; }
        public int CurrentEmote { get; set; }
        public int CoinCount { get; set; }
        public int TicketCount { get; set; }
        public bool HasBattlePass { get; set; }
        public short AiBehaviorIndex { get; set; }
        public int TotalBattles { get; set; }
        public int TotalWins { get; set; }
        public int TotalKills { get; set; }
        public int DoubleKills { get; set; }
        public int TripleKills { get; set; }
        public int ItemsCollected { get; set; }
        public int GunsCollected { get; set; }
        public int SupplyDrop { get; set; }
        public int SupplyCreates { get; set; }
        public int Experience { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Character> Characters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Emote> Emotes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flag> Flags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Parachute> Parachutes { get; set; }
        public virtual Character Character { get; set; }
        public virtual Emote Emote { get; set; }
        public virtual Flag Flag { get; set; }
        public virtual Parachute Parachute { get; set; }
    }
}
